<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_giro_5301483351</name>
   <tag></tag>
   <elementGuidId>5dca725e-e76d-4473-a6d5-a4b849f64df9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[3]/div/div/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Giro IDR5301483351Rp • • • • • • • • • •&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d22871c0-a326-4c2b-af1f-c0b627b7adc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-rwo3vd</value>
      <webElementGuid>2469077b-16f6-4bca-b9d4-7b93d1bb047d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Giro IDR5301483351Rp • • • • • • • • • •</value>
      <webElementGuid>0a5fcfcf-cbaf-48d6-bf04-520c385b06a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;MuiBox-root css-1pbvwnm&quot;]/div[@class=&quot;css-9x1v4i&quot;]/div[@class=&quot;MuiBox-root css-y68ggl&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 css-ogpv5o&quot;]/div[@class=&quot;MuiBox-root css-1g7fbw9&quot;]/div[@class=&quot;css-rwo3vd&quot;]</value>
      <webElementGuid>02da7140-a708-4296-a935-91c8586f85bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]/div/div/div/div[3]</value>
      <webElementGuid>fe6a3722-a4ba-4b54-bfd3-84e71602aad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp • • • • • • • • • •'])[2]/following::div[1]</value>
      <webElementGuid>cc38725d-a3f9-4d94-bcda-2cf30c12adf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giro IDR'])[2]/following::div[3]</value>
      <webElementGuid>580541f1-24b9-463f-af9b-f0b521764dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[3]</value>
      <webElementGuid>6de3a215-6395-4c05-b862-57e6ed1f5da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Giro IDR5301483351Rp • • • • • • • • • •' or . = 'Giro IDR5301483351Rp • • • • • • • • • •')]</value>
      <webElementGuid>a2a703ec-370f-46ad-8c40-1789a3e2a11f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
