<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_170.50</name>
   <tag></tag>
   <elementGuidId>e6c8052a-6e3a-4ffa-8783-9691cfb45ce2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.amount > span.price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='opc-sidebar']/div/table/tbody/tr/td/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;$170.50&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b6c8cfef-d052-4fb8-9e7d-797476a22bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>13d429dc-fcc5-4379-be35-fb5cbbfc0bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>text: getValue(), attr: {'data-th': title}</value>
      <webElementGuid>ed9e4886-3d18-4e60-aac1-0dc63684f53f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-th</name>
      <type>Main</type>
      <value>Cart Subtotal</value>
      <webElementGuid>80670bca-3325-4126-8f90-1a02ae5f3d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$170.50</value>
      <webElementGuid>548f86e3-36cb-4801-a689-d8b80124c184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opc-sidebar&quot;)/div[@class=&quot;opc-block-summary&quot;]/table[@class=&quot;data table table-totals&quot;]/tbody[1]/tr[@class=&quot;totals sub&quot;]/td[@class=&quot;amount&quot;]/span[@class=&quot;price&quot;]</value>
      <webElementGuid>63158fb6-f3b7-4acf-a749-c4f69a95753a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc-sidebar']/div/table/tbody/tr/td/span</value>
      <webElementGuid>c56b6b67-d606-4817-a346-ab5b09b273d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart Subtotal'])[1]/following::span[1]</value>
      <webElementGuid>db63b266-b45e-4fe9-a1a5-c93d853d9282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Summary'])[2]/following::span[1]</value>
      <webElementGuid>43c305f5-192d-4383-81f1-ca3daeb27634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping'])[2]/preceding::span[1]</value>
      <webElementGuid>5798d02c-f649-4ec7-ac4c-6627990ed8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flat Rate - Fixed'])[1]/preceding::span[2]</value>
      <webElementGuid>0a0e04ba-9362-4f8b-8ac2-8ec830c09c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$170.50']/parent::*</value>
      <webElementGuid>98d122da-1c82-4f7b-a94a-b0a5543cc6bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/table/tbody/tr/td/span</value>
      <webElementGuid>8a465d5d-4d1b-48fb-8a48-ac58015b1c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$170.50' or . = '$170.50')]</value>
      <webElementGuid>281d09d4-d00b-442c-81f0-337b565d04ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
