<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Shop with postgres</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>72694d6b-224a-422d-8710-bf3d3762bdeb</testSuiteGuid>
   <testCaseLink>
      <guid>1ffab162-eff1-4a57-9eab-56af733aee24</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sauce Demo/login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>cee3789f-20e6-463e-ae7b-ab8db769d165</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Sauce Demo/db_buyer</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92c0eed8-6f5f-460b-b223-182f7e0b3bee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>076446db-3c98-4045-b715-7f32de771dff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cee3789f-20e6-463e-ae7b-ab8db769d165</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>first</value>
         <variableId>4108100e-7ea5-4f4c-a177-77695b8f0a3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cee3789f-20e6-463e-ae7b-ab8db769d165</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>last</value>
         <variableId>2f59c64c-b35c-41e4-b86b-7969a8d3ecf7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cee3789f-20e6-463e-ae7b-ab8db769d165</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>post</value>
         <variableId>16604064-001f-48c4-b31e-285e1f10b3c1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
