<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>color_item5</name>
   <tag></tag>
   <elementGuidId>afa1bb77-ddce-42bd-935f-672bfef19e95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.swatch-opt-776 > div.swatch-attribute.color > div.swatch-attribute-options.clearfix > #option-label-color-93-item-52</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='option-label-color-93-item-52'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;Supernova Sport Pant Rating: 87% 3 Reviews As low as $36.00 32333436 Add to Cart&quot;i >> internal:label=&quot;Gray&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>30556124-2797-4e62-bf94-33d5e168a741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swatch-option color</value>
      <webElementGuid>aafcd8fc-0575-4932-8300-c79eba71d731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-label-color-93-item-52</value>
      <webElementGuid>f29b942d-c2be-4507-b166-ecf2c732ac5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f57cf1e7-b42a-4652-a78c-9652d6fdbcf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>16112bce-0c0d-4b8d-9b80-8f6facad15c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>option-label-color-93</value>
      <webElementGuid>f0596500-355d-4bc9-ad49-3e22e63bb947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>243750c7-4fce-42c3-9581-7051d7fdfb7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-type</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>dbb012a6-eaef-486f-9674-76a97da3a718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-id</name>
      <type>Main</type>
      <value>52</value>
      <webElementGuid>23d25f48-1b88-4f14-9e1b-9681f9665731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-label</name>
      <type>Main</type>
      <value>Gray</value>
      <webElementGuid>256df074-b074-446b-9f5e-ace631ee1c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Gray</value>
      <webElementGuid>8c576822-1bef-46bd-b316-0ace9b897eb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-tooltip-value</name>
      <type>Main</type>
      <value>#8f8f8f</value>
      <webElementGuid>a226e31d-bcea-4817-9c9a-bbcb08ce000d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>3945e2fb-b3fa-4b2f-ade6-0fef1be48b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>thumb-width</name>
      <type>Main</type>
      <value>110</value>
      <webElementGuid>920bdfac-7b2a-4b9b-a5f5-e0c1874853f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>thumb-height</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>4030dbd4-caa1-49dd-b72f-d28434067717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;products wrapper grid products-grid&quot;]/ol[@class=&quot;products list items product-items&quot;]/li[@class=&quot;item product product-item&quot;]/div[@class=&quot;product-item-info&quot;]/div[@class=&quot;product details product-item-details&quot;]/div[@class=&quot;swatch-opt-776&quot;]/div[@class=&quot;swatch-attribute color&quot;]/div[@class=&quot;swatch-attribute-options clearfix&quot;]/div[@id=&quot;option-label-color-93-item-52&quot;]</value>
      <webElementGuid>36c54c57-f986-47fb-88df-626bed8e4189</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='option-label-color-93-item-52'])[2]</value>
      <webElementGuid>4016d052-2120-4c08-8fda-6b0d2a67d950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[3]/div/div[3]/ol/li[9]/div/div/div[3]/div[2]/div/div[2]</value>
      <webElementGuid>46a1a8d3-29c7-45a2-867b-4a3eba9fc097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/div/div/div[3]/div[2]/div/div[2]</value>
      <webElementGuid>53b466cf-e702-4352-8e42-444130a73ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'option-label-color-93-item-52']</value>
      <webElementGuid>c9c4664f-9c17-42a7-87b5-66e66d1c4389</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
